#ifndef __options_dlg__
#define __options_dlg__

/**
@file
Subclass of OptionsBaseDlg, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "options_base_dlg.h"

/** Implementing OptionsBaseDlg */
class OptionsDlg : public OptionsBaseDlg
{
public:
	/** Constructor */
	OptionsDlg( wxWindow* parent, int id = wxID_ANY, wxString title = wxT("Options"), wxPoint pos = wxDefaultPosition, wxSize size = wxSize( 465,489 ), int style = wxDEFAULT_DIALOG_STYLE );
};

#endif // __options_dlg__
