dynamic_cast<wxFlatNotebook*>(myNotebook)
static_cast<wxFlatNotebook*>(myNotebook)
reinterpret_cast<wxFlatNotebook*>(myNotebook)
const_cast<wxFlatNotebook>(myNotebook)
((std::vector<wxString>&)strVec)
(wxFlatNotebook*)myNotebook
this
*this
Class::DoTheWork(myVector.GetName())